---
language: ruby
cache: bundler
rvm:
  - 2.7.1
before_install: gem install bundler -v 2.1.4

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - levon@createthree.com
    on_failure: change
    on_success: never
